// The only module that talks to glyph. Everything else works with the small
// API returned by getGlyphEngine(). src/vendor/glyph.js is generated by
// scripts/bundle-glyph.mjs, see scripts/glyph-entry.js for what it contains.
import {
  glyph,
  bitmap,
  defineGlyphConfig,
  defineGlyphSchema,
  resourceLease,
  createRasterCodecProgram,
  bitmapCodec,
  defineCodecBuffers,
  id as codecId,
  createBitmapBaker,
  bitmapBakerFromCore,
  createFontLibrary,
  createFontBaker,
  bakeFontPipeline,
  createResolvedRasterBakePlan,
} from "../vendor/glyph.js";

export const WASM_FILES = ["text-shaper.wasm", "font-baker.wasm", "bitmap-baker.wasm"];

// The engine needs one raster format per font. We rasterize glyphs ourselves,
// so this is the smallest strike glyph accepts, covering a single space.
const RASTER = bitmap({ strikes: [8], coverage: { text: " " } });

const SCHEMA = defineGlyphSchema({
  program: (_b, p) => p,
  buffer: (_b, i) => i,
  material: (_b, m) => m,
  transform: (_b, t) => t,
  batch: (_b, i) => i,
  instance: (_b, i) => i,
  instanceSpan: (_b, i) => i,
});

const SYSTEM_BUFFERS = defineCodecBuffers({
  stableGlyphId: {
    id: codecId.buffer("c3-text-glyph/stable-glyph"),
    scalar: "u32",
    lanes: ["stableGlyphId"],
  },
  placementSlot: {
    id: codecId.buffer("c3-text-glyph/placement-slot"),
    scalar: "u32",
    lanes: ["placementSlot"],
  },
});

const CAPABILITIES = Object.freeze({
  capabilities: Object.freeze([
    "storage-buffers",
    "alias-vec2",
    "alias-vec4",
    "ordered-direct",
  ]),
  maxBufferBytes: 16 * 1024 * 1024,
  updateAlignment: 4,
  coalesceGapBytes: 128,
  rangeCallPenaltyBytes: 256,
  maxBuffersPerDraw: 8,
  maxResourcesPerDraw: 4,
  maxIndirectDraws: 0,
  fragmentationBudget: 8,
  wholeBufferThresholdBasisPoints: 7500,
});

// We only use glyph for shaping and layout. The renderer side of the config
// accepts everything and draws nothing.
const CONFIG = defineGlyphConfig({
  schema: SCHEMA,
  encode: ({ ids }) => ({
    descriptor: {
      capabilitySets: [CAPABILITIES],
      programs: [
        createRasterCodecProgram(bitmapCodec, {
          namespace: "c3-text-glyph",
          system: SYSTEM_BUFFERS,
          capabilitySet: CAPABILITIES,
          transformMode: "direct",
          ids,
        }),
      ],
    },
  }),
  resolve: ({ resourceName, payload }) =>
    resourceLease({ name: resourceName, resource: payload }, () => {}),
  renderer: () => ({
    decode: () => ({ result: undefined, commit() {}, discard() {} }),
    syncTransforms() {},
    dispose() {},
  }),
  root: {
    create: (ctx) => ctx.create({ services: ctx.services }, { boundary: {} }),
  },
});

let enginePromise = null;

// loadWasm(filename) resolves to the bytes of one of WASM_FILES. glyph is a
// singleton per page, so the first caller's loader wins.
export function getGlyphEngine(loadWasm) {
  if (!enginePromise) enginePromise = createEngine(loadWasm);
  return enginePromise;
}

async function createEngine(loadWasm) {
  const [shaperWasm, fontBakerWasm, bitmapBakerWasm] = await Promise.all(WASM_FILES.map(loadWasm));
  await glyph.init({ wasm: shaperWasm });
  const fontBaker = await createFontBaker(fontBakerWasm);
  const bitmapModule = bitmapBakerFromCore(await createBitmapBaker(bitmapBakerWasm));

  async function runtimeBake(request) {
    const rasters = (request.rasters ?? []).map((r) => {
      if (r.kind !== "bitmap")
        throw new Error(`[Text Glyph] unexpected raster kind ${r.kind}`);
      return createResolvedRasterBakePlan(
        bitmapModule,
        { artifact: "embedded" },
        r.descriptor,
        r.rasterKey
      );
    });
    const result = await bakeFontPipeline({
      fontBaker,
      source: request.source,
      fontFaceIndex: 0,
      rasters,
      ...(request.unicodeRanges === undefined
        ? {}
        : { unicodeRanges: request.unicodeRanges }),
    });
    return result.composed.artifacts[0].bytes;
  }

  const library = createFontLibrary({ runtimeBake });
  const handle = glyph.handle("c3-text-glyph", CONFIG);

  return {
    // bytes: Uint8Array of a TTF/OTF file. Returns a glyph Font lease.
    loadFont(bytes) {
      return library.loadFont({ source: { bytes }, runtimeBake }, RASTER);
    },
    createText(state) {
      return handle.services.createText(state);
    },
  };
}
